# Generated by Django 3.2.7 on 2021-09-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idealist_app', '0004_alter_idea_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Idea_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idealist_app.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idealist_app.employee')),
            ],
        ),
    ]
